# Generated by Django 5.1.4 on 2025-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='job_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='job_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
